services:
  - type: web
    name: hemathchandran-portfolio
    runtime: node
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: cd src/server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000