services:
  - type: web
    name: hemath-portfolio-backend
    env: node
    buildCommand: cd src/server && npm install
    startCommand: cd src/server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001